import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import SideNav from "@/components/side-nav";
import LinkedInPreview from "@/components/linkedin-preview";
import AppSidebar from "@/components/app-sidebar";
import AppSidebarInset from "@/components/providers/app-sidebar-inset";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <SidebarProvider className="w-fit" defaultOpen={true}>
            <SideNav />
            <SidebarTrigger />
          </SidebarProvider>

          <SidebarProvider
            style={{
              // @ts-ignore
              "--sidebar-width": "555px",
            }}
          >
            <AppSidebar>
              <AppSidebarInset>{children}</AppSidebarInset>
            </AppSidebar>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
